# yaml file

units: us
metrics:
  # Temperature and Comfort
  temperature: true # air temperature at 2â€¯m above ground
  feels_like: true # apparent temperature, "feels like"
  dew_point: true # dew point temperature
  wind_chill: true # For Cold Climates
  heat_index: true # for hot climates

  # Humidity and Precipitation
  humidity: true # relative humidity (%)
  precipitation: true # precipitation amount (mm/in)
  precipitation_probability: true # chance of rain (%)
  precipitation_type: true # rain, snow, sleet, hail
  snowfall: true # snow accumulation (mm/in)
  snow_depth: true # current snow on ground (cm/in)
  freezing_rain: true # boolean / intensity

  # Wind
  wind_speed: true # speed at reference height (m/s, km/h, mph)
  wind_gusts: true # maximum gusts
  wind_direction: true # direction in degrees
  wind_vector: true # optional vector form (u/v components)

  # Cloud and Visibility
  cloud_cover: true # % of sky covered
  cloud_base: true # altitude of lowest clouds (optional)
  visibility: true # in km/miles

  # Weather Codes / Phonemena
  weather_code: true # numeric or coded condition (WMO code)
  weather_description: true # human-readable string

  # Solar and UV
  uv_index: true # UV index
  sunrise: true # timestamp
  sunset: true # timestamp
  daylight_duration: true # optional

  # Pressure and Atmospheric
  pressure: true # mean sea-level pressure
  pressure_trend: true # optional rising/falling indicator
  altimeter: true # aviation reference

  # Derived and Feels Like
  feels_like_temperature: false # for hot, humid conditions
  air_quality_index: false # Fed Regulated
  pollen_index: false

sources:
  - open_meteo
  - nws
  - weatherapi
  - mateostat
  - accuweather
  - weatherbit

output:
  format: json
  save_to_file: true
